env:
  browser: true
  es2021: true
  node: true

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"

parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"

plugins:
  - "@typescript-eslint"
  - "prettier"

rules:
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/no-explicit-any": "warn"
  "prettier/prettier": "error"
  "@typescript-eslint/no-unused-expressions":
    - "error"
    - { "allowShortCircuit": true, "allowTernary": true }
